### ISSUE TITLE
Testing Party Bug: Login Issue using Google Account

### ISSUE THREAD

**Issue by simarmehta** [gcivil-nyu-org/wed-fall24-team1#199] opened 2024-11-18 20:56 UTC
### Google Sign In

**Steps to Reproduce:**
1. Use the provided link and click on "Google Sign-In."
2. When redirected to the Google Sign-In page, click "Cancel."

**Observed Behavior:**
- Upon canceling the Google Sign-In, the user is taken to a completely different UI and screen, instead of being returned to the last screen in case of a login failure.
- Clicking on "Login" from this screen leads to another UI that is different from the expected login UI.

**Screenshots:**

https://github.com/user-attachments/assets/3aecabb9-43ab-4b8c-b743-303e75043f32

**Expected Behavior:**
- Canceling the Google Sign-In should redirect the user back to the last screen.
- The redirection and page used for login should remain consistent throughout the login process.

**Comment by ahhcash** [comment] 2024-11-18 21:42
Google login is known to be buggy sometimes, we’ve listed this in our
testing doc

**Comment by omerfarukbasar** [comment] 2024-11-19 00:07
@simarmehta This is mentioned within the testing document.
<img width="738" alt="Screenshot 2024-11-18 at 7 05 40 PM" src="https://github.com/user-attachments/assets/d352b89f-d5bc-4f8c-ba01-a38f452b405a">

**Comment by simarmehta** [comment] 2024-11-19 00:30
That's alright but this is about redirection back to the appropriate page, it is maybe going back to old UI or something like that?

**Comment by omerfarukbasar** [comment] 2024-11-19 00:47
@simarmehta That's not our UI, it's something from google. Again this is a **_known issue_** from the Google authentication that we mentioned in the document earlier. Sometimes it works as intended and sometimes it does what you showed.

**Comment by ahhcash** [comment] 2024-11-19 03:56
Closing as discussed, we are tracking this separately

**Closed as not planned by ahhcash** 2024-11-19 03:56 UTC
Labels: duplicate
